version: '3.9'

services:
    mongo:
      image: mongo
      container_name: mongo
      environment:
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
      volumes:
        - mongo-volume:/vol/mongo
      ports:
        - ${DB_PORT}:${DB_PORT}
      networks:
        - mongo-net
      restart: unless-stopped

volumes:
  mongo-volume:

networks:
  mongo-net:
    driver: bridge
    name: mongo-net
