version: "3"

dotenv: [".env"]

tasks:
  build:
    cmds:
      - docker compose -f walking-school.yml up -d --build

  run:
    cmds:
       - docker compose -f walking-school.yml up -d
 
  stop:
    cmds:
      - docker compose -f walking-school.yml down

  
  swaginit:
    cmds:
      - swag init -d cmd,internal/api/handler,internal/model
