version: "3"

dotenv: [".env"]

tasks:
  build:
    cmds:
      - docker compose -f walking-school.yml up -d --build

  stop:
    cmds:
      - docker compose -f mongo.yml down
      - docker compose -f walking-school.yml down

  run:
    # env:
    #   DB_HOST: localhost
    cmds:
      # - docker compose -f walking-school.yml up -d
      - go run cmd/main.go
  
  swaginit:
    cmds:
      - swag init -d cmd,internal/api/handler,internal/model
