version: "3"

dotenv: [".env"]

tasks:
  run:
    cmds:
       - docker compose -f walking-school.yml up -d
      # - go run cmd/main.go
 
  stop:
    cmds:
      - docker compose -f walking-school.yml down

  
  swaginit:
    cmds:
      - swag init -d cmd,internal/api/handler,internal/model
