version: '3.9'

services:
    walking-school:
      # env_file:
      #   - .env
      build: .
      container_name: walking-school
      ports:
        - ${APP_PORT}:${APP_PORT}
      networks:
        - mongo-net
        - client-server-net 
      restart: unless-stopped
    
networks:
  mongo-net:
    external: true
    name: mongo-net

  client-server-net:
    external: true
    name: client-server-net
