version: '3.9'

services:
    walking-school:
      # env_file:
      #   - .env
      build: .
      container_name: walking-school
      ports:
        - ${APP_PORT}:${APP_PORT}
      networks:
        - localnet
      restart: unless-stopped
    
networks:
  localnet:
    driver: bridge
    name: localnet
