version: '3.9'

services:
    walking-school:
      env_file:
        - .env
      build: .
      container_name: walking-school
      ports:
        - ${APP_PORT}:${APP_PORT}
      restart: unless-stopped

