basePath: /
definitions:
  model.CreateHeroSwagger:
    properties:
      description:
        example: some description
        type: string
      image:
        example: stunning image
        type: string
      title:
        example: some title
        type: string
    type: object
  model.CreateProjectSwagger:
    properties:
      age_category:
        example: ""
        type: string
      category:
        example: ""
        type: string
      description:
        example: ""
        type: string
      image:
        example: ""
        type: string
      link:
        example: ""
        type: string
      period:
        example:
        - ""
        items:
          type: string
        type: array
      title:
        example: ""
        type: string
    type: object
  model.CreateUserSwagger:
    properties:
      combat_certificate:
        example: true
        type: boolean
      disability_certificate:
        example:
        - ""
        items:
          type: string
        type: array
      email:
        example: example1@gmail.com
        type: string
      international_passport:
        example:
        - ""
        items:
          type: string
        type: array
      location:
        example: ""
        type: string
      name:
        example: ""
        type: string
      patronymic:
        example: ""
        type: string
      phone:
        example: "+380631122331"
        type: string
      physical_action_constraints:
        example:
        - ""
        items:
          type: string
        type: array
      surname:
        example: ""
        type: string
      weight_below_95:
        example: true
        type: boolean
    type: object
  model.Project:
    properties:
      age_category:
        example: ""
        type: string
      category:
        example: ""
        type: string
      created:
        example: ""
        type: string
      description:
        example: ""
        type: string
      id:
        example: ""
        type: string
      image:
        example: ""
        type: string
      is_active:
        example: true
        type: boolean
      last_modified:
        example: ""
        type: string
      link:
        example: ""
        type: string
      period:
        example:
        - ""
        items:
          type: string
        type: array
      title:
        example: ""
        type: string
    required:
    - age_category
    - category
    - description
    - image
    - link
    - period
    - title
    type: object
  model.Response:
    properties:
      code:
        type: integer
      messsage:
        type: string
    type: object
  model.UpdateHeroSwagger:
    properties:
      description:
        example: some description
        type: string
      id:
        example: ""
        type: string
      image:
        example: stunning image
        type: string
      title:
        example: some title
        type: string
    type: object
  model.UpdateUserSwagger:
    properties:
      combat_certificate:
        example: true
        type: boolean
      disability_certificate:
        example:
        - ""
        items:
          type: string
        type: array
      email:
        example: example1@gmail.com
        type: string
      id:
        example: ""
        type: string
      international_passport:
        example:
        - ""
        items:
          type: string
        type: array
      location:
        example: ""
        type: string
      name:
        example: ""
        type: string
      patronymic:
        example: ""
        type: string
      phone:
        example: "+380631122331"
        type: string
      physical_action_constraints:
        example:
        - ""
        items:
          type: string
        type: array
      surname:
        example: ""
        type: string
      weight_below_95:
        example: true
        type: boolean
    type: object
host: localhost:7000
info:
  contact:
    email: etverya12@gmail.com
    name: Yehor Tverytinov
  title: Walking-School backend API
  version: "1.0"
paths:
  /hero:
    get:
      consumes:
      - application/json
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get all heros.
      tags:
      - hero
    post:
      consumes:
      - application/json
      parameters:
      - description: Hero
        in: body
        name: Hero
        required: true
        schema:
          $ref: '#/definitions/model.CreateHeroSwagger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Create hero .
      tags:
      - hero
    put:
      consumes:
      - application/json
      parameters:
      - description: Hero
        in: body
        name: Hero
        required: true
        schema:
          $ref: '#/definitions/model.UpdateHeroSwagger'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update hero by id.
      tags:
      - hero
  /hero/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Delete hero by id.
      tags:
      - hero
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get hero by id.
      tags:
      - hero
  /project:
    get:
      consumes:
      - application/json
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get all projects.
      tags:
      - project
    post:
      consumes:
      - application/json
      parameters:
      - description: Project
        in: body
        name: Project
        required: true
        schema:
          $ref: '#/definitions/model.CreateProjectSwagger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Create project.
      tags:
      - project
    put:
      consumes:
      - application/json
      parameters:
      - description: Project
        in: body
        name: Project
        required: true
        schema:
          $ref: '#/definitions/model.Project'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update project by id.
      tags:
      - project
  /project/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Delete project by id.
      tags:
      - project
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get project by id.
      tags:
      - project
  /user:
    get:
      consumes:
      - application/json
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get all users.
      tags:
      - user
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserSwagger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Create user.
      tags:
      - user
    put:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUserSwagger'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update user by id.
      tags:
      - user
  /user/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Delete user by id.
      tags:
      - user
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get user by id.
      tags:
      - user
swagger: "2.0"
